package entities;
/**
 * Describes the types of possible requests that can occur in the system
 */
public enum RequestType {
	READ_ORDER, WRITE_ORDER, UPDATE_GUESTS, UPDATE_DATE, LOGIN_REQUEST,REGISTER_REQUEST,READ_EMAIL, CANCEL_REQUEST,
    GET_TAKEN_SLOTS,ORDER_NUMBER, CHECK_AVAILABLE, RESERVE_TABLE,JOIN_WAITLIST,LEAVE_WAITLIST, UPDATE_DETAILS, ORDER_HISTORY,
    GET_ALL_ACTIVE_ORDERS, GET_ALL_SUBSCRIBERS, TRY_SEAT,CHECK_CONFCODE
}
